[build]
rustc-wrapper = "/usr/local/bin/sccache"
target = "x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc" 

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc" 

[target.x86_64-apple-darwin]
rustflags = ["-L/usr/local/osxcross/target/macports/pkgs/opt/local/lib", "-L/usr/local/osxcross/target/SDK/MacOSX13.3.sdk/usr/lib"]
linker = "x86_64-apple-darwin22.4-clang"
ar = "x86_64-apple-darwin22.4-ar"

[target.aarch64-apple-darwin]
rustflags = ["-L/usr/local/osxcross/target/macports/pkgs/opt/local/lib", "-L/usr/local/osxcross/target/SDK/MacOSX13.3.sdk/usr/lib"]
linker = "aarch64-apple-darwin22.4-clang"
ar = "aarch64-apple-darwin22.4-ar"
